CREATE TABLE ULTRA_CAD_23.BI_DIMENSION_TIPO_MEDIO_PAGO(
    ID_TIPO_MEDIO_PAGO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TIPO_MEDIO_PAGO nvarchar(50)
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_ESTADO_RECLAMO(
    ID_ESTADO_RECLAMO INT PRIMARY KEY IDENTITY(1,1),
    ESTADO_RECLAMO NVARCHAR(255) NOT NULL
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO(
    ID_RANGO_ETARIO INT PRIMARY KEY IDENTITY(1,1),
    RANGO_ETARIO NVARCHAR(10)
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_LOCAL(
    ID_LOCAL INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_LOCAL nvarchar(100)
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD (
	ID_PROVINCIA_LOCALIDAD INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
	PROVINCIA NVARCHAR(255) NOT NULL,
	LOCALIDAD NVARCHAR(255) NOT NULL
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_TIPO_MOVILIDAD (
	ID_TIPO_MOVILIDAD INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIPO_MOVILIDAD NVARCHAR(50) NOT NULL
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO (
	ID_RANGO_HORARIO INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
	RANGO_HORARIO NVARCHAR(50) NOT NULL
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_ESTADO_ENVIO_MENSAJERIA (
	ID_ESTADO_ENVIO_MENSAJERIA INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
	ESTADO_ENVIO_MENSAJERIA NVARCHAR(50) NOT NULL
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_TIPO_PAQUETE (
	ID_TIPO_PAQUETE INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIPO_PAQUETE NVARCHAR(255) NOT NULL
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_ESTADO_PEDIDO(
    ID_ESTADO_PEDIDO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ESTADO_PEDIDO NVARCHAR(255)
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_TIPO_LOCAL(
    ID_TIPO_LOCAL INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIPO_LOCAL NVARCHAR(50)
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_DIA(
    ID_DIA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    DIA NVARCHAR(50)
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_TIEMPO(
    ID_TIEMPO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ANIO INT NOT NULL,
    MES INT NOT NULL 
);

CREATE TABLE  ULTRA_CAD_23.BI_DIMENSION_TIPO_RECLAMO(
    ID_TIPO_RECLAMO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TIPO_RECLAMO NVARCHAR(255)
);

CREATE TABLE  ULTRA_CAD_23.BI_HECHO_PEDIDO(
    ID_PROVINCIA_LOCALIDAD  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD(ID_PROVINCIA_LOCALIDAD),
    ID_TIPO_CATEGORIA_LOCAL  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIPO_LOCAL(ID_TIPO_LOCAL),
    ID_DIA INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_DIA(ID_DIA),
    ID_RANGO_HORARIO  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO(ID_RANGO_HORARIO),
    ID_TIEMPO INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIEMPO(ID_TIEMPO),
    ID_LOCAL INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_LOCAL(ID_LOCAL),
    ID_ESTADO_PEDIDO  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_ESTADO_PEDIDO(ID_ESTADO_PEDIDO),
    ID_TIPO_MOVILIDAD  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIPO_MOVILIDAD(ID_TIPO_MOVILIDAD),
    ID_RANGO_ETARIO_REPARTIDOR  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO(ID_RANGO_ETARIO),
	ID_RANGO_ETARIO_USUARIO  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO(ID_RANGO_ETARIO),
	ID_TIPO_MEDIO_PAGO  INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIPO_MEDIO_PAGO(ID_TIPO_MEDIO_PAGO),
    MONTO_TOTAL DECIMAL(18,2) NOT NULL,
    VALOR_ENVIO DECIMAL(18,2) NOT NULL,
    DESVIO_TIEMPO_ENTREGA INT NOT NULL,
    MONTO_TOTAL_CUPONES DECIMAL(18,2) NOT NULL,
    CALIFICACION DECIMAL(18,0) NOT NULL,
	CANTIDAD_PEDIDOS INT,
    PRIMARY KEY (ID_PROVINCIA_LOCALIDAD, ID_TIPO_CATEGORIA_LOCAL, ID_DIA, ID_RANGO_HORARIO, ID_TIEMPO, ID_LOCAL, ID_ESTADO_PEDIDO, ID_TIPO_MOVILIDAD, ID_RANGO_ETARIO_REPARTIDOR, ID_RANGO_ETARIO_USUARIO, ID_TIPO_MEDIO_PAGO)
);

CREATE TABLE  ULTRA_CAD_23.BI_HECHO_ENVIO_DE_MENSAJERIA (
	ID_TIPO_MOVILIDAD INT  NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIPO_MOVILIDAD(ID_TIPO_MOVILIDAD),
	ID_TIEMPO INT  NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIEMPO(ID_TIEMPO),
	ID_DIA INT  NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_DIA(ID_DIA),
	ID_RANGO_ETARIO INT  NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO(ID_RANGO_ETARIO),
	ID_RANGO_HORARIO INT  NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO(ID_RANGO_HORARIO),
	ID_PROVINCIA_LOCALIDAD INT  NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD(ID_PROVINCIA_LOCALIDAD),
	ID_ESTADO_ENVIO_MENSAJERIA INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_ESTADO_ENVIO_MENSAJERIA(ID_ESTADO_ENVIO_MENSAJERIA),
	ID_TIPO_PAQUETE INT NOT NULL FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIPO_PAQUETE(ID_TIPO_PAQUETE),
	DESVIO_TIEMPO_ENTREGA INT NOT NULL,
	VALOR_ASEGURADO DECIMAL(18,2) NOT NULL,
	CANTIDAD_ENVIOS INT,
	PRIMARY KEY(ID_TIPO_MOVILIDAD, ID_TIEMPO, ID_DIA, ID_RANGO_ETARIO, ID_RANGO_HORARIO, ID_PROVINCIA_LOCALIDAD, ID_ESTADO_ENVIO_MENSAJERIA, ID_TIPO_PAQUETE)
);

CREATE TABLE  ULTRA_CAD_23.BI_HECHO_RECLAMO(
	ID_LOCAL INT FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_LOCAL(ID_LOCAL),
	ID_DIA INT FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_DIA(ID_DIA),
	ID_TIEMPO INT FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_TIEMPO(ID_TIEMPO),
	ID_RANGO_ETARIO INT FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO(ID_RANGO_ETARIO),
	ID_ESTADO_RECLAMO INT FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_ESTADO_RECLAMO(ID_ESTADO_RECLAMO),
	ID_RANGO_HORARIO INT FOREIGN KEY REFERENCES  ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO(ID_RANGO_HORARIO),
	ID_TIPO_RECLAMO INT FOREIGN KEY REFERENCES ULTRA_CAD_23.BI_DIMENSION_TIPO_RECLAMO(ID_TIPO_RECLAMO),
	TIEMPO_RESOLUCION DECIMAL(18,2),
	MONTO_CUPON_GENERADO DECIMAL(18,2),
	CANTIDAD_RECLAMOS INT,
	PRIMARY KEY (ID_LOCAL ,ID_DIA ,ID_TIEMPO ,ID_RANGO_ETARIO ,ID_ESTADO_RECLAMO , ID_RANGO_HORARIO, ID_TIPO_RECLAMO)
);

------------------------------------------------------INSERTS DIMENSIONES-----------------------------------------------------

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_TIPO_MEDIO_PAGO (TIPO_MEDIO_PAGO)
SELECT TIPO_MEDIO_PAGO FROM ULTRA_CAD_23.TIPO_MEDIO_PAGO 

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_ESTADO_RECLAMO (ESTADO_RECLAMO)
SELECT RECLAMO_DESCRIPCION FROM ULTRA_CAD_23.ESTADO_DE_RECLAMO

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO(RANGO_ETARIO) VALUES ('<25'), ('25-35'), ('35-55'), ('>55');

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_LOCAL(NOMBRE_LOCAL)
SELECT LOCAL_NOMBRE FROM ULTRA_CAD_23.LOCALES 

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD(PROVINCIA, LOCALIDAD)
SELECT P.PROVINCIA_NOMBRE, LOCALIDAD_NOMBRE FROM ULTRA_CAD_23.LOCALIDAD L JOIN ULTRA_CAD_23.PROVINCIA P ON (L.PROVINCIA_COD=P.PROVINCIA_COD)

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_TIPO_MOVILIDAD(TIPO_MOVILIDAD)
SELECT MOVILIDAD_NOMBRE FROM ULTRA_CAD_23.MOVILIDAD

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO(RANGO_HORARIO) VALUES ('08:00 - 10:00'),('10:00 - 12:00'),('12:00 - 14:00'),
('14:00 - 16:00'),('16:00 - 18:00'),('18:00 - 20:00'),('20:00 - 22:00'),('22:00 - 00:00');

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_ESTADO_ENVIO_MENSAJERIA(ESTADO_ENVIO_MENSAJERIA)
SELECT DISTINCT E.ESTADO_NOMBRE FROM ULTRA_CAD_23.ENVIO_DE_MENSAJERIA M JOIN ULTRA_CAD_23.ESTADO E ON (E.ESTADO_NRO = M.ENVIO_MENSAJERIA_ESTADO)

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_TIPO_PAQUETE(TIPO_PAQUETE)
SELECT PAQUETE_TIPO FROM ULTRA_CAD_23.PAQUETE

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_ESTADO_PEDIDO(ESTADO_PEDIDO)
SELECT DISTINCT E.ESTADO_NOMBRE FROM ULTRA_CAD_23.PEDIDO P JOIN ULTRA_CAD_23.ESTADO E ON (E.ESTADO_NRO = P.PEDIDO_ESTADO)

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_TIPO_LOCAL(TIPO_LOCAL)
SELECT TIPO_LOCAL_DESCRIPCION FROM ULTRA_CAD_23.TIPO_LOCAL

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_DIA(DIA) VALUES ('Domingo'), ('Lunes'),('Martes'),('Miercoles'),('Jueves'),('Viernes'),('Sabado');

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_TIEMPO(ANIO, MES)
(SELECT DISTINCT YEAR(RECLAMO_FECHA), MONTH(RECLAMO_FECHA) FROM ULTRA_CAD_23.RECLAMO 
UNION
SELECT DISTINCT YEAR(RECLAMO_FECHA_RESOLUCION), MONTH(RECLAMO_FECHA_RESOLUCION) FROM ULTRA_CAD_23.RECLAMO
UNION
SELECT DISTINCT YEAR(PEDIDO_FECHA_ENTREGA), MONTH(PEDIDO_FECHA_ENTREGA) FROM ULTRA_CAD_23.PEDIDO 
UNION
SELECT DISTINCT YEAR(PEDIDO_FECHA), MONTH(PEDIDO_FECHA) FROM ULTRA_CAD_23.PEDIDO 
UNION
SELECT DISTINCT YEAR(ENVIO_MENSAJERIA_FECHA), MONTH(ENVIO_MENSAJERIA_FECHA) FROM ULTRA_CAD_23.ENVIO_DE_MENSAJERIA 
UNION
SELECT DISTINCT YEAR(ENVIO_MENSAJERIA_FECHA_ENTREGA), MONTH(ENVIO_MENSAJERIA_FECHA_ENTREGA) FROM ULTRA_CAD_23.ENVIO_DE_MENSAJERIA
) ORDER BY 1

INSERT INTO ULTRA_CAD_23.BI_DIMENSION_TIPO_RECLAMO
SELECT RECLAMO_NOMBRE FROM ULTRA_CAD_23.TIPO_RECLAMO

----------------------------------------------------------FUNCIONES-----------------------------------------------------------

GO 

CREATE FUNCTION ULTRA_CAD_23.FUNCION_PROVINCIA_LOCALIDAD(@LOCALIDAD INT)
RETURNS INT
BEGIN
	RETURN (SELECT ID_PROVINCIA_LOCALIDAD FROM ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD 
	WHERE LOCALIDAD = (SELECT LOCALIDAD_NOMBRE FROM ULTRA_CAD_23.LOCALIDAD WHERE LOCALIDAD_COD = @LOCALIDAD)
	AND
	PROVINCIA = (SELECT PROVINCIA_NOMBRE 
					FROM ULTRA_CAD_23.LOCALIDAD L 
					JOIN ULTRA_CAD_23.PROVINCIA P ON (L.PROVINCIA_COD=P.PROVINCIA_COD) 
					WHERE L.LOCALIDAD_COD=@LOCALIDAD))
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_LOCAL(@PEDIDO_NRO DECIMAL(18,0)) --LOS RECLAMOS TIENEN EL NUMERO DE PEDIDO, Y EL PEDIDO TAMBIEN
RETURNS INT
BEGIN
	RETURN (SELECT LOCAL_NRO FROM ULTRA_CAD_23.PEDIDO WHERE PEDIDO_NRO = @PEDIDO_NRO) 
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_RANGO_ETARIO(@FECHA_NACIMIENTO DATE)
RETURNS INT
BEGIN
	DECLARE @EDAD INT, @ID INT
	SET @EDAD = DATEDIFF(YEAR, @FECHA_NACIMIENTO, GETDATE())
	IF (@EDAD < 25) BEGIN SET @ID = (SELECT ID_RANGO_ETARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO WHERE RANGO_ETARIO = '<25') END
	ELSE IF (@EDAD >= 25 AND @EDAD <= 35) BEGIN SET @ID = (SELECT ID_RANGO_ETARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO WHERE RANGO_ETARIO = '25-35') END
	ELSE IF (@EDAD > 35 AND @EDAD <= 55) BEGIN SET @ID = (SELECT ID_RANGO_ETARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO WHERE RANGO_ETARIO = '35-55') END
	ELSE BEGIN SET @ID = (SELECT ID_RANGO_ETARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO WHERE RANGO_ETARIO = '>55') END
	RETURN @ID
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_TIPO_MEDIO_PAGO(@PEDIDO_NRO INT)
RETURNS INT 
BEGIN
	RETURN (SELECT M.TIPO_MEDIO_PAGO_COD FROM ULTRA_CAD_23.PEDIDO P 
	JOIN ULTRA_CAD_23.MEDIO_PAGO E ON (P.MEDIO_PAGO_NRO = E.MEDIO_PAGO_NRO)
	JOIN ULTRA_CAD_23.TIPO_MEDIO_PAGO M ON (E.MEDIO_PAGO_TIPO = M.TIPO_MEDIO_PAGO_COD)
	WHERE PEDIDO_NRO = @PEDIDO_NRO)
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_TIPO_MOVILIDAD(@REPARTIDOR_COD INT)
RETURNS INT 
BEGIN
	RETURN (SELECT ID_TIPO_MOVILIDAD FROM ULTRA_CAD_23.BI_DIMENSION_TIPO_MOVILIDAD
	WHERE TIPO_MOVILIDAD = (SELECT MOVILIDAD_NOMBRE FROM ULTRA_CAD_23.MOVILIDAD M JOIN
	ULTRA_CAD_23.REPARTIDOR R ON M.MOVILIDAD_COD = R.REPARTIDOR_TIPO_MOVILIDAD
	WHERE REPARTIDOR_CODIGO = @REPARTIDOR_COD))
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_ESTADO_ENVIO_MENSAJERIA(@ESTADO_NRO INT)
RETURNS INT 
BEGIN
	RETURN (SELECT ID_ESTADO_ENVIO_MENSAJERIA FROM ULTRA_CAD_23.BI_DIMENSION_ESTADO_ENVIO_MENSAJERIA
	WHERE ESTADO_ENVIO_MENSAJERIA = (SELECT ESTADO_NOMBRE FROM ULTRA_CAD_23.ESTADO
	WHERE ESTADO_NRO = @ESTADO_NRO))
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_TIPO_PAQUETE(@TIPO_PAQUETE_COD INT)
RETURNS INT 
BEGIN
	RETURN (SELECT ID_TIPO_PAQUETE FROM ULTRA_CAD_23.BI_DIMENSION_TIPO_PAQUETE
	WHERE TIPO_PAQUETE = (SELECT PAQUETE_TIPO FROM ULTRA_CAD_23.PAQUETE
	WHERE PAQUETE_COD = @TIPO_PAQUETE_COD))
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_RANGO_HORARIO(@FECHA DATETIME)
RETURNS INT 
BEGIN
	DECLARE @HORA INT, @ID INT
	SET @HORA = DATEPART(HOUR, @FECHA)
	IF (@HORA BETWEEN 8 AND 10) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '08:00 - 10:00') END
	ELSE IF (@HORA BETWEEN 10 AND 12) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '10:00 - 12:00') END
	ELSE IF (@HORA BETWEEN 12 AND 14) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '12:00 - 14:00') END
	ELSE IF (@HORA BETWEEN 14 AND 16) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '14:00 - 16:00') END
	ELSE IF (@HORA BETWEEN 16 AND 18) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '16:00 - 18:00') END
	ELSE IF (@HORA BETWEEN 18 AND 20) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '18:00 - 20:00') END
	ELSE IF (@HORA BETWEEN 20 AND 22) BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '20:00 - 22:00') END
	ELSE BEGIN SET @ID = (SELECT ID_RANGO_HORARIO FROM ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO WHERE RANGO_HORARIO = '22:00 - 00:00') END
	RETURN @ID
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_ESTADO_PEDIDO(@ESTADO INT)
RETURNS INT 
BEGIN
    RETURN(SELECT ID_ESTADO_PEDIDO FROM ULTRA_CAD_23.BI_DIMENSION_ESTADO_PEDIDO
           WHERE ESTADO_PEDIDO = (SELECT ESTADO_NOMBRE FROM ULTRA_CAD_23.ESTADO WHERE ESTADO_NRO = @ESTADO)) 
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_TIPO_LOCAL(@tipo_local INT)
RETURNS INT
BEGIN
    RETURN(SELECT ID_TIPO_LOCAL FROM ULTRA_CAD_23.BI_DIMENSION_TIPO_LOCAL
            WHERE TIPO_LOCAL = (SELECT TIPO_LOCAL_DESCRIPCION FROM ULTRA_CAD_23.TIPO_LOCAL WHERE LOCAL_TIPO_NRO = @tipo_local))
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_DIA(@FECHA DATETIME)
RETURNS INT 
BEGIN
    RETURN(SELECT ID_DIA FROM ULTRA_CAD_23.BI_DIMENSION_DIA WHERE ID_DIA = datepart(weekday,@FECHA))
END

GO

CREATE FUNCTION ULTRA_CAD_23.FUNCION_TIEMPO(@FECHA DATETIME)
RETURNS INT
BEGIN
    RETURN(SELECT ID_TIEMPO FROM ULTRA_CAD_23.BI_DIMENSION_TIEMPO WHERE ANIO = YEAR(@FECHA) AND MES = MONTH(@FECHA))
END

GO

-----------------------------------------------------------TABLAS DE HECHOS----------------------------------------------------------

INSERT INTO ULTRA_CAD_23.BI_HECHO_RECLAMO
SELECT
	ULTRA_CAD_23.FUNCION_LOCAL(PEDIDO_NUMERO) ,
	ULTRA_CAD_23.FUNCION_DIA(RECLAMO_FECHA) , 
	ULTRA_CAD_23.FUNCION_TIEMPO(RECLAMO_FECHA) ,
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(O.OPERADOR_RECLAMO_FECHA_NACIMIENTO) ,
	R.ESTADO_RECLAMO ,
	ULTRA_CAD_23.FUNCION_RANGO_HORARIO(RECLAMO_FECHA) ,
	R.RECLAMO_TIPO,
	AVG(DATEDIFF(MINUTE, RECLAMO_FECHA, RECLAMO_FECHA_RESOLUCION)), 
	SUM(C.CUPON_MONTO), 
	COUNT(R.RECLAMO_NRO)
FROM ULTRA_CAD_23.RECLAMO R 
	JOIN ULTRA_CAD_23.OPERADOR O ON (R.OPERADOR_NRO = O.OPERADOR_NRO)
	JOIN ULTRA_CAD_23.CUPON_RECLAMO CR ON (CR.RECLAMO_NRO = R.RECLAMO_NRO)
	JOIN ULTRA_CAD_23.CUPON C ON (C.CUPON_NRO = CR.CUPON_NRO)
GROUP BY 
	ULTRA_CAD_23.FUNCION_LOCAL(PEDIDO_NUMERO) ,
	ULTRA_CAD_23.FUNCION_DIA(RECLAMO_FECHA) , 
	ULTRA_CAD_23.FUNCION_TIEMPO(RECLAMO_FECHA) ,
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(O.OPERADOR_RECLAMO_FECHA_NACIMIENTO) , 
	R.ESTADO_RECLAMO , 
	ULTRA_CAD_23.FUNCION_RANGO_HORARIO(RECLAMO_FECHA),
	R.RECLAMO_TIPO

INSERT INTO ULTRA_CAD_23.BI_HECHO_ENVIO_DE_MENSAJERIA
SELECT
	ULTRA_CAD_23.FUNCION_TIPO_MOVILIDAD(E.REPARTIDOR_CODIGO),
	ULTRA_CAD_23.FUNCION_TIEMPO(ENVIO_MENSAJERIA_FECHA), 
	ULTRA_CAD_23.FUNCION_DIA(ENVIO_MENSAJERIA_FECHA), 
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(R.REPARTIDOR_FECHA_NAC),
	ULTRA_CAD_23.FUNCION_RANGO_HORARIO(ENVIO_MENSAJERIA_FECHA), 
	ULTRA_CAD_23.FUNCION_PROVINCIA_LOCALIDAD(E.ENVIO_MENSAJERIA_LOCALIDAD), 
	ULTRA_CAD_23.FUNCION_ESTADO_ENVIO_MENSAJERIA(ENVIO_MENSAJERIA_ESTADO), 
	ULTRA_CAD_23.FUNCION_TIPO_PAQUETE(PAQUETE_COD), 
	SUM(ENVIO_MENSAJERIA_TIEMPO_ESTIMADO - ABS(DATEDIFF(MINUTE, ENVIO_MENSAJERIA_FECHA, ENVIO_MENSAJERIA_FECHA_ENTREGA))), 
	SUM(ENVIO_MENSAJERIA_VALOR_ASEGURADO),
	COUNT(ENVIO_MENSAJERIA_NRO)
	FROM ULTRA_CAD_23.ENVIO_DE_MENSAJERIA E JOIN 
	ULTRA_CAD_23.REPARTIDOR R ON (E.REPARTIDOR_CODIGO = R.REPARTIDOR_CODIGO)
GROUP BY ULTRA_CAD_23.FUNCION_TIPO_MOVILIDAD(E.REPARTIDOR_CODIGO), 
	ULTRA_CAD_23.FUNCION_TIEMPO(ENVIO_MENSAJERIA_FECHA), 
	ULTRA_CAD_23.FUNCION_DIA(ENVIO_MENSAJERIA_FECHA), 
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(R.REPARTIDOR_FECHA_NAC), 
	ULTRA_CAD_23.FUNCION_RANGO_HORARIO(ENVIO_MENSAJERIA_FECHA), 
	ULTRA_CAD_23.FUNCION_PROVINCIA_LOCALIDAD(E.ENVIO_MENSAJERIA_LOCALIDAD), 
	ULTRA_CAD_23.FUNCION_ESTADO_ENVIO_MENSAJERIA(ENVIO_MENSAJERIA_ESTADO), 
	ULTRA_CAD_23.FUNCION_TIPO_PAQUETE(PAQUETE_COD)


INSERT INTO ULTRA_CAD_23.BI_HECHO_PEDIDO
SELECT DISTINCT
	ULTRA_CAD_23.FUNCION_PROVINCIA_LOCALIDAD(D.DIRECCION_USUARIO_LOCALIDAD), 
	ULTRA_CAD_23.FUNCION_TIPO_LOCAL(T.LOCAL_TIPO_NRO),
	ULTRA_CAD_23.FUNCION_DIA(PEDIDO_FECHA), 
	ULTRA_CAD_23.FUNCION_RANGO_HORARIO(PEDIDO_FECHA),
	ULTRA_CAD_23.FUNCION_TIEMPO(PEDIDO_FECHA),
	ULTRA_CAD_23.FUNCION_LOCAL(P.LOCAL_NRO),
	ULTRA_CAD_23.FUNCION_ESTADO_PEDIDO(PEDIDO_ESTADO),
	ULTRA_CAD_23.FUNCION_TIPO_MOVILIDAD(P.REPARTIDOR_CODIGO),
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(R.REPARTIDOR_FECHA_NAC),
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(U.USUARIO_FECHA_NAC),
	M.TIPO_MEDIO_PAGO_COD,
	SUM(PEDIDO_TOTAL_SERVICIO),
	SUM(PEDIDO_PRECIO_ENVIO),
	SUM(PEDIDO_TIEMPO_ESTIMADO_ENTREGA - DATEDIFF(MINUTE, PEDIDO_FECHA, PEDIDO_FECHA_ENTREGA)),
	SUM(PEDIDO_TOTAL_CUPONES),
	SUM(PEDIDO_CALIFICACION),
	COUNT(PEDIDO_NRO)
	FROM ULTRA_CAD_23.PEDIDO p
	JOIN ULTRA_CAD_23.LOCALES l ON (p.local_nro = l.local_nro)
	JOIN ULTRA_CAD_23.TIPO_LOCAL t ON (l.local_tipo = t.local_tipo_nro)
	JOIN ULTRA_CAD_23.USUARIO U ON (P.USUARIO_NRO = U.USUARIO_NRO)
	JOIN ULTRA_CAD_23.DIRECCION D ON (P.USUARIO_NRO = D.USUARIO_NRO AND P.PEDIDO_DIRECCION = D.DIRECCION_CODIGO)
	JOIN ULTRA_CAD_23.REPARTIDOR R ON (R.REPARTIDOR_CODIGO = P.REPARTIDOR_CODIGO)
	JOIN ULTRA_CAD_23.MEDIO_PAGO MP ON (MP.MEDIO_PAGO_NRO = P.MEDIO_PAGO_NRO)
	JOIN ULTRA_CAD_23.TIPO_MEDIO_PAGO M ON (M.TIPO_MEDIO_PAGO_COD = MP.MEDIO_PAGO_TIPO)
GROUP BY
	ULTRA_CAD_23.FUNCION_PROVINCIA_LOCALIDAD(D.DIRECCION_USUARIO_LOCALIDAD), 
	ULTRA_CAD_23.FUNCION_TIPO_LOCAL(T.LOCAL_TIPO_NRO),
	ULTRA_CAD_23.FUNCION_DIA(PEDIDO_FECHA), 
	ULTRA_CAD_23.FUNCION_RANGO_HORARIO(PEDIDO_FECHA),
	ULTRA_CAD_23.FUNCION_TIEMPO(PEDIDO_FECHA),
	ULTRA_CAD_23.FUNCION_LOCAL(P.LOCAL_NRO),
	ULTRA_CAD_23.FUNCION_ESTADO_PEDIDO(PEDIDO_ESTADO),
	ULTRA_CAD_23.FUNCION_TIPO_MOVILIDAD(P.REPARTIDOR_CODIGO),
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(R.REPARTIDOR_FECHA_NAC),
	ULTRA_CAD_23.FUNCION_RANGO_ETARIO(U.USUARIO_FECHA_NAC),
	M.TIPO_MEDIO_PAGO_COD

GO

-----------------------------------------VIEWS-------------------------------------------------------

CREATE VIEW ULTRA_CAD_23.BI_PROMEDIO_DESVIO_TIEMPO_DE_ENTREGA(MOVILIDAD, DIA, RANGO_HORARIO, DESVIO)
AS
SELECT TIPO_MOVILIDAD, DIA, RANGO_HORARIO, DESVIO_PROMEDIO FROM 
(SELECT
	COALESCE(P.ID_TIPO_MOVILIDAD, E.ID_TIPO_MOVILIDAD) ID_MOVILIDAD,
	COALESCE(P.ID_DIA, E.ID_DIA) ID_DIA,
	COALESCE(P.ID_RANGO_HORARIO, E.ID_RANGO_HORARIO) ID_HORARIO,
	CONVERT(FLOAT, SUM(COALESCE(E.DESVIO_TIEMPO_ENTREGA,0)+COALESCE(P.DESVIO_TIEMPO_ENTREGA,0))/
	(SUM(COALESCE(E.CANTIDAD_ENVIOS,0)+COALESCE(P.CANTIDAD_PEDIDOS,0)))) DESVIO_PROMEDIO
 FROM ULTRA_CAD_23.BI_HECHO_PEDIDO P FULL JOIN ULTRA_CAD_23.BI_HECHO_ENVIO_DE_MENSAJERIA E ON
	(E.ID_TIPO_MOVILIDAD = P.ID_TIPO_MOVILIDAD AND E.ID_DIA = P.ID_DIA AND E.ID_RANGO_HORARIO = P.ID_RANGO_HORARIO)
	GROUP BY P.ID_TIPO_MOVILIDAD, P.ID_DIA, P.ID_RANGO_HORARIO, E.ID_TIPO_MOVILIDAD, E.ID_RANGO_HORARIO, E.ID_DIA) P
JOIN ULTRA_CAD_23.BI_DIMENSION_TIPO_MOVILIDAD M ON (P.ID_MOVILIDAD = M.ID_TIPO_MOVILIDAD)
JOIN ULTRA_CAD_23.BI_DIMENSION_DIA D ON (D.ID_DIA = P.ID_DIA)
JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO R ON (P.ID_HORARIO = R.ID_RANGO_HORARIO)


GO

CREATE VIEW ULTRA_CAD_23.BI_TOTAL_CUPONES_POR_MES(ANIO, MES, RANGO_ETARIO, MONTO_TOTAL_CUPONES)
AS
SELECT T.ANIO, MES, RANGO_ETARIO, SUM(MONTO_TOTAL_CUPONES) TOTAL_CUPONES FROM ULTRA_CAD_23.BI_HECHO_PEDIDO P
JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO E ON (E.ID_RANGO_ETARIO = P.ID_RANGO_ETARIO_USUARIO)
JOIN ULTRA_CAD_23.BI_DIMENSION_TIEMPO T ON (T.ID_TIEMPO = P.ID_TIEMPO)
GROUP BY T.ANIO, MES, RANGO_ETARIO

GO

CREATE VIEW ULTRA_CAD_23.BI_PROMEDIO_CALIFICACION_MENSUAL(ANIO, MES, CALIFICACION_PROMEDIO)
AS
SELECT ANIO, MES, SUM(CALIFICACION)/SUM(CANTIDAD_PEDIDOS) FROM ULTRA_CAD_23.BI_HECHO_PEDIDO P
JOIN ULTRA_CAD_23.BI_DIMENSION_TIEMPO T ON (T.ID_TIEMPO = P.ID_TIEMPO)
GROUP BY ANIO, MES

GO

CREATE VIEW ULTRA_CAD_23.BI_PORCENTAJE_MENSUAL_REPARTICIONES_POR_LOCALIDAD(ANIO, MES, RANGO_ETARIO_REPARTIDOR, LOCALIDAD, PORCENTAJE)
AS
SELECT ANIO, MES, RANGO_ETARIO, LOCALIDAD, PROMEDIO FROM
(SELECT COALESCE(P.ID_TIEMPO, E.ID_TIEMPO) ID_TIEMPO,
    COALESCE(ID_RANGO_ETARIO_REPARTIDOR, ID_RANGO_ETARIO) ID_RANGO_ETARIO,
    COALESCE(P.ID_PROVINCIA_LOCALIDAD, E.ID_PROVINCIA_LOCALIDAD) ID_LOCALIDAD,
    CONVERT(FLOAT,(COALESCE(TOTALPED,0) + COALESCE(TOTALENV,0))*100)/
    ((SELECT SUM(CANTIDAD_PEDIDOS) CANTIDAD FROM ULTRA_CAD_23.BI_HECHO_PEDIDO) +
        (SELECT SUM(CANTIDAD_ENVIOS) CANTIDAD FROM ULTRA_CAD_23.BI_HECHO_ENVIO_DE_MENSAJERIA)) PROMEDIO
    FROM (SELECT ID_TIEMPO,
        ID_RANGO_ETARIO_REPARTIDOR,
        ID_PROVINCIA_LOCALIDAD,
        SUM(CANTIDAD_PEDIDOS) TOTALPED
        FROM ULTRA_CAD_23.BI_HECHO_PEDIDO
        GROUP BY ID_TIEMPO, ID_RANGO_ETARIO_REPARTIDOR, ID_PROVINCIA_LOCALIDAD) P
    FULL JOIN (SELECT ID_TIEMPO,
        ID_RANGO_ETARIO,
        ID_PROVINCIA_LOCALIDAD,
        SUM(CANTIDAD_ENVIOS) TOTALENV
        FROM  ULTRA_CAD_23.BI_HECHO_ENVIO_DE_MENSAJERIA
        GROUP BY ID_TIEMPO, ID_RANGO_ETARIO, ID_PROVINCIA_LOCALIDAD) E
    ON P.ID_TIEMPO = E.ID_TIEMPO AND ID_RANGO_ETARIO_REPARTIDOR = ID_RANGO_ETARIO AND P.ID_PROVINCIA_LOCALIDAD = E.ID_PROVINCIA_LOCALIDAD) P
JOIN ULTRA_CAD_23.BI_DIMENSION_TIEMPO T ON (P.ID_TIEMPO = T.ID_TIEMPO)
JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO E ON (E.ID_RANGO_ETARIO = P.ID_RANGO_ETARIO)
JOIN ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD L ON (P.ID_LOCALIDAD = L.ID_PROVINCIA_LOCALIDAD)
GO


CREATE VIEW ULTRA_CAD_23.BI_PROMEDIO_MENSUAL_VALOR_ASEGURADO(TIPO_PAQUETE, PROMEDIO_VALOR_ASEGURADO)
AS
SELECT T.TIPO_PAQUETE, AVG(VALOR_ASEGURADO) FROM ULTRA_CAD_23.BI_HECHO_ENVIO_DE_MENSAJERIA E 
	JOIN ULTRA_CAD_23.BI_DIMENSION_TIPO_PAQUETE T ON (E.ID_TIPO_PAQUETE = T.ID_TIPO_PAQUETE)
GROUP BY T.TIPO_PAQUETE

GO

CREATE VIEW ULTRA_CAD_23.BI_CANTIDAD_RECLAMOS_POR_LOCAL(CANTIDAD_RECLAMOS, LOCAL, DIA, RANGO_HORARIO)
AS
SELECT SUM(CANTIDAD_RECLAMOS), L.NOMBRE_LOCAL, D.DIA, H.RANGO_HORARIO FROM ULTRA_CAD_23.BI_HECHO_RECLAMO R
	JOIN ULTRA_CAD_23.BI_DIMENSION_LOCAL L ON (R.ID_LOCAL = L.ID_LOCAL)
	JOIN ULTRA_CAD_23.BI_DIMENSION_DIA D ON (D.ID_DIA = R.ID_DIA)
	JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO H ON (H.ID_RANGO_HORARIO = R.ID_RANGO_HORARIO)
GROUP BY L.NOMBRE_LOCAL, D.DIA, H.RANGO_HORARIO

GO

CREATE VIEW ULTRA_CAD_23.BI_TIEMPO_PROMEDIO_RESOLUCION(TIEMPO_PROMEDIO_RESOLUCION, TIPO_RECLAMO, RANGO_ETARIO_OPERADOR)
AS
SELECT SUM(TIEMPO_RESOLUCION)/SUM(CANTIDAD_RECLAMOS), T.TIPO_RECLAMO, E.RANGO_ETARIO  FROM ULTRA_CAD_23.BI_HECHO_RECLAMO R
	JOIN ULTRA_CAD_23.BI_DIMENSION_TIPO_RECLAMO T ON (R.ID_TIPO_RECLAMO = T.ID_TIPO_RECLAMO)
	JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_ETARIO E ON (E.ID_RANGO_ETARIO = R.ID_RANGO_ETARIO)
GROUP BY T.TIPO_RECLAMO, E.RANGO_ETARIO

GO

CREATE VIEW ULTRA_CAD_23.BI_MONTO_CUPONES(MONTO_MENSUAL, MES, ANIO) 
AS
SELECT SUM(MONTO_CUPON_GENERADO), T.MES, T.ANIO FROM ULTRA_CAD_23.BI_HECHO_RECLAMO R
	JOIN ULTRA_CAD_23.BI_DIMENSION_TIEMPO T ON (R.ID_TIEMPO = T.ID_TIEMPO)
GROUP BY T.MES, T.ANIO
go

CREATE VIEW ULTRA_CAD_23.BI_MAYOR_CANTIDAD_PEDIDOS
AS
WITH DATOS(CANTIDAD, DIA, RANGO_HORARIO, LOCALIDAD, TIPO_LOCAL, TIEMPO) AS (SELECT SUM(CANTIDAD_PEDIDOS), DIA, R.RANGO_HORARIO, L.LOCALIDAD, T.TIPO_LOCAL, TI.ID_TIEMPO FROM ULTRA_CAD_23.BI_HECHO_PEDIDO P 
JOIN ULTRA_CAD_23.BI_DIMENSION_DIA D ON (P.ID_DIA=D.ID_DIA)
JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO R ON (R.ID_RANGO_HORARIO = P.ID_RANGO_HORARIO)
JOIN ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD L ON (L.ID_PROVINCIA_LOCALIDAD = P.ID_PROVINCIA_LOCALIDAD)
JOIN ULTRA_CAD_23.BI_DIMENSION_TIPO_LOCAL T ON (T.ID_TIPO_LOCAL = P.ID_TIPO_CATEGORIA_LOCAL)
JOIN ULTRA_CAD_23.BI_DIMENSION_TIEMPO TI ON (TI.ID_TIEMPO = P.ID_TIEMPO)
GROUP BY D.DIA, R.RANGO_HORARIO, L.LOCALIDAD, T.TIPO_LOCAL, TI.ID_TIEMPO)
SELECT MAXIMA_CANTIDAD, DIA, RANGO_HORARIO, D.LOCALIDAD, D.TIPO_LOCAL, D.TIEMPO FROM DATOS D
JOIN (SELECT MAX(CANTIDAD) MAXIMA_CANTIDAD, LOCALIDAD, TIPO_LOCAL, TIEMPO FROM DATOS
GROUP BY LOCALIDAD, TIPO_LOCAL, TIEMPO) M ON 
(D.LOCALIDAD = M.LOCALIDAD AND D.TIPO_LOCAL = M.TIPO_LOCAL AND D.TIEMPO = M.TIEMPO AND M.MAXIMA_CANTIDAD = CANTIDAD)

go

CREATE VIEW ULTRA_CAD_23.BI_MONTO_TOTAL_NO_COBRADO(LOCAL, DIA, RANGO_HORARIO, MONTO_TOTAL_CANCELADO)
AS
SELECT NOMBRE_LOCAL, DIA, RANGO_HORARIO, SUM(MONTO_TOTAL)
FROM ULTRA_CAD_23.BI_HECHO_PEDIDO P
JOIN ULTRA_CAD_23.BI_DIMENSION_LOCAL L ON (P.ID_LOCAL = L.ID_LOCAL)
JOIN ULTRA_CAD_23.BI_DIMENSION_DIA D ON (P.ID_DIA = D.ID_DIA)
JOIN ULTRA_CAD_23.BI_DIMENSION_RANGO_HORARIO R ON (R.ID_RANGO_HORARIO = P.ID_RANGO_HORARIO)
WHERE ID_ESTADO_PEDIDO = (SELECT ID_ESTADO_PEDIDO FROM ULTRA_CAD_23.BI_DIMENSION_ESTADO_PEDIDO WHERE ESTADO_PEDIDO = 'Estado Mensajeria Cancelado')
GROUP BY L.NOMBRE_LOCAL, D.DIA, R.RANGO_HORARIO

GO

CREATE VIEW ULTRA_CAD_23.BI_VALOR_PROMEDIO_MENSUAL_ENVIOS(LOCALIDAD, MES, ANIO, PROMEDIO)
AS
SELECT LOCALIDAD, MES, ANIO, CONVERT(FLOAT, SUM(VALOR_ENVIO)/SUM(CANTIDAD_PEDIDOS)) FROM ULTRA_CAD_23.BI_HECHO_PEDIDO P 
JOIN ULTRA_CAD_23.BI_DIMENSION_PROVINCIA_LOCALIDAD L ON (P.ID_PROVINCIA_LOCALIDAD = L.ID_PROVINCIA_LOCALIDAD)
JOIN ULTRA_CAD_23.BI_DIMENSION_TIEMPO T ON (P.ID_TIEMPO = T.ID_TIEMPO)
GROUP BY LOCALIDAD, MES, ANIO